### ISSUE TITLE
242_input_night_included.txt Stackoverflow Bug

### ISSUE THREAD

**Issue by jerryjeremiah** [sfm999/Slide_Game#1]
I don't understand why you toggle night_mode twice:

```
      if(night_mode == DAY){
        night_mode = NIGHT;
      }else if(night_mode == NIGHT){
        night_mode = DAY;
      }
      int game_one = shift_left(day_realm, laser_y);
      int game_two = shift_left(night_realm, laser_y);
      if(game_one == LOSE || game_two == LOSE)
      {
        disable = 0;
        print_realm(day_realm, laser_y, SHIFT);
        printf("Game Lost!\n");
        break;
      }else{
        if(night_mode == DAY){
          print_realm(day_realm, laser_y, SHIFT);
          night_mode = NIGHT;
        }else if(night_mode == NIGHT){
          print_realm(night_realm, laser_y, SHIFT);
          night_mode = DAY;
        }
      }
```

When you run that code, it toggles the night_mode, shifts both realms left, draws the board, and then toggles the night mode again.  So if night_mode equals DAY and you press 3 it displays the night realm and then leaves night_mode equal to DAY so that when you fire the laser it destroys things on the day_realm even though the night realm is displayed:

```
      if(night_mode == DAY)
      {
        fire_laser(day_realm, laser_y);
        if(print_realm(day_realm, laser_y, FIRE_LASER) == WIN)
        {
          printf("You Won!\n");
          break;
        }
      }else if(night_mode == NIGHT)
      {
        fire_laser(night_realm, laser_y);
        if(print_realm(night_realm, laser_y, FIRE_LASER) == WIN)
        {
          printf("You Won!\n");
          break;
        }
      }
```

So I think the solution is to not toggle night_mode the second time:

```
      if(night_mode == DAY){
        night_mode = NIGHT;
      }else if(night_mode == NIGHT){
        night_mode = DAY;
      }
      int game_one = shift_left(day_realm, laser_y);
      int game_two = shift_left(night_realm, laser_y);
      if(game_one == LOSE || game_two == LOSE)
      {
        disable = 0;
        print_realm(day_realm, laser_y, SHIFT);
        printf("Game Lost!\n");
        break;
      }else{
        if(night_mode == DAY){
          print_realm(day_realm, laser_y, SHIFT);
          // night_mode = NIGHT; // don't do this!
        }else if(night_mode == NIGHT){
          print_realm(night_realm, laser_y, SHIFT);
          // night_mode = DAY; // don't do this!
        }
      }
```

**Comment by sfm999** [comment]
You're correct my man. I spotted it a little while in after looking deeper in to the code. That's awesome that you spotted it. 

I've changed it to the following: 

```
      int game_one = shift_left(day_realm, laser_y);
      int game_two = shift_left(night_realm, laser_y);
      if(game_one == LOSE || game_two == LOSE)
      {
        disable = 0;
        print_realm(day_realm, laser_y, SHIFT);
        printf("Game Lost!\n");
        break;
      }
      if(night_mode == DAY){
        night_mode = NIGHT;
        print_realm(night_realm, laser_y, SHIFT);
      }else if(night_mode == NIGHT){
        night_mode = DAY;
        print_realm(day_realm, laser_y, SHIFT);
      }
```
Nice job spotting it though. Thanks for taking the time to look :)

**Comment by spongurat** [comment]
> I don't understand why you toggle night_mode twice:
> 
> ```
>       if(night_mode == DAY){
>         night_mode = NIGHT;
>       }else if(night_mode == NIGHT){
>         night_mode = DAY;
>       }
>       int game_one = shift_left(day_realm, laser_y);
>       int game_two = shift_left(night_realm, laser_y);
>       if(game_one == LOSE || game_two == LOSE)
>       {
>         disable = 0;
>         print_realm(day_realm, laser_y, SHIFT);
>         printf("Game Lost!\n");
>         break;
>       }else{
>         if(night_mode == DAY){
>           print_realm(day_realm, laser_y, SHIFT);
>           night_mode = NIGHT;
>         }else if(night_mode == NIGHT){
>           print_realm(night_realm, laser_y, SHIFT);
>           night_mode = DAY;
>         }
>       }
> ```
> 
> When you run that code, it toggles the night_mode, shifts both realms left, draws the board, and then toggles the night mode again. So if night_mode equals DAY and you press 3 it displays the night realm and then leaves night_mode equal to DAY so that when you fire the laser it destroys things on the day_realm even though the night realm is displayed:
> 
> ```
>       if(night_mode == DAY)
>       {
>         fire_laser(day_realm, laser_y);
>         if(print_realm(day_realm, laser_y, FIRE_LASER) == WIN)
>         {
>           printf("You Won!\n");
>           break;
>         }
>       }else if(night_mode == NIGHT)
>       {
>         fire_laser(night_realm, laser_y);
>         if(print_realm(night_realm, laser_y, FIRE_LASER) == WIN)
>         {
>           printf("You Won!\n");
>           break;
>         }
>       }
> ```
> 
> So I think the solution is to not toggle night_mode the second time:
> 
> ```
>       if(night_mode == DAY){
>         night_mode = NIGHT;
>       }else if(night_mode == NIGHT){
>         night_mode = DAY;
>       }
>       int game_one = shift_left(day_realm, laser_y);
>       int game_two = shift_left(night_realm, laser_y);
>       if(game_one == LOSE || game_two == LOSE)
>       {
>         disable = 0;
>         print_realm(day_realm, laser_y, SHIFT);
>         printf("Game Lost!\n");
>         break;
>       }else{
>         if(night_mode == DAY){
>           print_realm(day_realm, laser_y, SHIFT);
>           // night_mode = NIGHT; // don't do this!
>         }else if(night_mode == NIGHT){
>           print_realm(night_realm, laser_y, SHIFT);
>           // night_mode = DAY; // don't do this!
>         }
>       }
> ```

You're correct my man. I spotted it a little while in after looking deeper in to the code. That's awesome that you spotted it. 

I've changed it to the following: 

```
      int game_one = shift_left(day_realm, laser_y);
      int game_two = shift_left(night_realm, laser_y);
      if(game_one == LOSE || game_two == LOSE)
      {
        disable = 0;
        print_realm(day_realm, laser_y, SHIFT);
        printf("Game Lost!\n");
        break;
      }
      if(night_mode == DAY){
        night_mode = NIGHT;
        print_realm(night_realm, laser_y, SHIFT);
      }else if(night_mode == NIGHT){
        night_mode = DAY;
        print_realm(day_realm, laser_y, SHIFT);
      }
```
Nice job spotting it though. Thanks for taking the time to look :)
